# For complete documentation see: https://zmk.dev/docs/config/build-config

# This file contains the build configuration for your keyboard(s).
# Add additional boards/shields here to build them as well.

include:
  - board: nrf52840dk/nrf52840
    shield: corne
  - board: nrf52840dk/nrf52840
    shield: corne_left
  - board: nrf52840dk/nrf52840
    shield: corne_right
  - board: adafruit_feather_nrf52840
    shield: corne
  - board: adafruit_feather_nrf52840
    shield: corne_left
  - board: adafruit_feather_nrf52840
    shield: corne_right

# For additional boards/shields, add them to the include list above.
# Example for split keyboards:
#   - board: nrf52840dk/nrf52840
#     shield: lily58_left
#   - board: nrf52840dk/nrf52840
#     shield: lily58_right