# For complete documentation see: https://zmk.dev/docs/config/build-config

# This file contains the build configuration for your keyboard(s).
# Add additional boards/shields here to build them as well.

include:
  - board: nice_nano
    shield: corne_romac
  - board: nice_nano
    shield: corne_romac_left
  - board: nice_nano
    shield: corne_romac_right
  - board: nice_nano_v2
    shield: corne_romac
  - board: nice_nano_v2
    shield: corne_romac_left
  - board: nice_nano_v2
    shield: corne_romac_right

# For additional boards/shields, add them to the include list above.
# Example for split keyboards:
#   - board: nice_nano
#     shield: lily58_left
#   - board: nice_nano
#     shield: lily58_right