manifest:
<<<<<<< HEAD
  version: "0.1"
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      url: https://github.com/zmkfirmware/zmk
    - name: zephyr
      remote: zephyrproject
      revision: v3.7.0
      url: https://github.com/zephyrproject-rtos/zephyr
=======
  version: "0.13"
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zephyr
      remote: zmkfirmware
      revision: v4.1.0+zmk-fixes
      clone-depth: 1
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_openisa
          - hal_nxp
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m
    - name: zmk
      remote: zmkfirmware
      revision: main
>>>>>>> d28344a (Add GitHub Actions workflow for ZMK builds)
  self:
    path: zmk-config